import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';
import './globals.css';

import Header from '@/components/Header';

const notoSans = Noto_Sans({
  weight: '400',
});

// const roboto = Roboto_Slab({
//   weight: '400',
// });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSans.className} flex flex-col mx-auto`}>
        <Header />
        <main className="grow lg:mx-auto lg:w-3/5">{children}</main>
      </body>
    </html>
  );
}
